# Generated by Django 5.0.14 on 2025-09-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fetchjob',
            name='kind',
            field=models.CharField(choices=[('top_n', 'Top N'), ('collection', 'Collection'), ('refresh', 'Refresh')], max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.category'),
        ),
    ]
