# Generated by Django 5.0.14 on 2025-09-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_category_alter_fetchjob_kind_game_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='families',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.family'),
        ),
    ]
