# Generated by Django 5.2.6 on 2025-09-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_family_game_families'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='owned_by',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='collection',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
