# Generated by Django 5.2.15 on 2026-06-21 13:57

from django.db import migrations, models


def _normalize_year_to_int_strings(apps, schema_editor):
    """Null out non-numeric ``year`` values so the CharField -> IntegerField
    cast below succeeds. Runs while ``year`` is still a CharField."""
    Game = apps.get_model("games", "Game")
    updates = []
    for game in Game.objects.all().iterator():
        raw = game.year
        if raw is None:
            continue
        text = str(raw).strip()
        normalized = text if text.lstrip("-").isdigit() else None
        if normalized != raw:
            game.year = normalized
            updates.append(game)
        if len(updates) >= 500:
            Game.objects.bulk_update(updates, ["year"])
            updates = []
    if updates:
        Game.objects.bulk_update(updates, ["year"])


def _year_int_to_str(apps, schema_editor):
    """Reverse: convert integer years back to strings."""
    Game = apps.get_model("games", "Game")
    updates = []
    for game in Game.objects.all().iterator():
        if game.year is None:
            continue
        game.year = str(game.year)
        updates.append(game)
        if len(updates) >= 500:
            Game.objects.bulk_update(updates, ["year"])
            updates = []
    if updates:
        Game.objects.bulk_update(updates, ["year"])


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_mechanic_game_mechanics"),
    ]

    operations = [
        migrations.RunPython(
            _normalize_year_to_int_strings, _year_int_to_str
        ),
        migrations.AlterField(
            model_name="game",
            name="avg_rating",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="bgg_rank",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="owned",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="game",
            name="type",
            field=models.CharField(
                choices=[("Base Game", "Base Game"), ("Expansion", "Expansion")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="weight",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="year",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="playercountrecommendation",
            name="count",
            field=models.IntegerField(db_index=True),
        ),
    ]
