# Generated by Django 5.2.6 on 2026-07-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_rttgame_alter_fetchjob_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGAGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='fetchjob',
            name='kind',
            field=models.CharField(choices=[('top_n', 'Top N'), ('collection', 'Collection'), ('refresh', 'Refresh'), ('rtt', 'Rally the Troops'), ('bga', 'Board Game Arena')], max_length=20),
        ),
    ]
